### ISSUE TITLE
Forking/Cloning doesn't copy over the Ephemeris

### ISSUE THREAD

**Issue by mfixstsci** [spacetelescope/jwst_gtvt#7]
Pip/Forking doesn't seem to copy over the ephemeris. @bholler and I need to look into this in detail.

**Comment by bholler** [comment]
@mfixstsci identified the issue in setup.py, line 91: The old ephemeris was listed under "package data" and so the setup file was attempting to add a non-existent file to the correct path. This resulted in the new ephemeris, which has a different name, being located in the topmost level of jwst_gtvt, and the code could not find it at the location it was told to look. This issue was solved by changing the name of the ephemeris file in setup.py to the new file name. A note was added to the Confluence page that provides a recipe for future updates of the tools (https://confluence.stsci.edu/pages/viewpage.action?pageId=123019428). 

This issue can be closed.

**Comment by mfixstsci** [comment]
Thanks @bholler!
